// <auto-generated />
using System;
using Login.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Login.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211106211849_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Login.Entidades.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveNuevamente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido = "Solorin",
                            Clave = "1234",
                            Fecha = new DateTime(2021, 11, 6, 17, 18, 48, 950, DateTimeKind.Local).AddTicks(7751),
                            Nombre = "Pedro",
                            NombreUsuario = "pedro"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellido = "Payano",
                            Clave = "1234",
                            Fecha = new DateTime(2021, 11, 6, 17, 18, 48, 953, DateTimeKind.Local).AddTicks(1269),
                            Nombre = "Manolo",
                            NombreUsuario = "mpayano"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
